r2dbc:
  connection:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres
    schema: public
    applicationName: reactive-caffeine-cache
server:
  port: 9999